root: true

extends:
  - react-app
  - plugin:jsx-a11y/recommended
  - airbnb
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
  - plugin:promise/recommended
  - plugin:sonarjs/recommended

rules:
  prettier/prettier:
    - error
    - {
        semi: false,
        trailingComma: all,
        singleQuote: true,
        printWidth: 80,
        tabWidth: 2,
        arrowParens: avoid,
    }
  arrow-body-style: off
  prefer-arrow-callback: off

parser: "@typescript-eslint/parser"

parserOptions:
  project: ./tsconfig.json
  ecmaVersion: 2021
  sourceType: module

env:
  es6: true
  browser: true
  node: true
